import turtle as t
t.shape("turtle")
t.bgcolor("black")
t.color("green")
t.speed(0)
for x in range (100):
    t.forward(50)
    t.left(90)
    t.forward(50)
    t.left(90)
    t.forward(50)
    t.right(90)
    t.forward(50)
    t.left(90)
    t.forward(50)
    t.left(90)
    t.forward(50)
    t.right(90)
    t.forward(50)
    t.left(90)
    t.forward(100+x)
